name: see
channels:
    - pytorch
    - defaults
    - conda-forge
dependencies:
    - python==3.6.13
    - pip
    - cudatoolkit
    - pytorch==1.10.1+cu111
    - torchvision==0.11.2+cu111
    - numpy
    - timm==0.4.12
    - jupyter
    - pip:
          - pillow
          - scipy
          - pytorch_metric_learning
          - wandb
          - pandas
